<h1 align="center">EQE512 MATRIX METHODS IN STRUCTURAL ANALYSIS 
<br>
<br>
Week 04
<br>
<br>
Truss System - Stifness Matrix & Beam Element</h1> 

<h3 align="center">Dr. Ahmet Anıl Dindar (adindar@gtu.edu.tr)</h3> 
<h4 align="center">2021 Fall  </h4> 

---
## Today's Topics

1- Truss System Stiffness Matrix Creation

2- Beam Element

## Truss System Stiffness Matrix Creation

In [239]:
import numpy as np
def member_stiffness_creator(member_props) :
    """
    E: modulus of elasticiy
    A: Area 
    Joint I
    Joint J
    
    Return 
    k_member    
    """
    
    delta_1 = member_props["jointJ"][0] - member_props["jointI"][0] 
    delta_2 = member_props["jointJ"][1] - member_props["jointI"][1] 

    length = (delta_1**2 + delta_2**2)**.5

    c1 = delta_1 / length
    c2 = delta_2 / length

    a = c1**2
    b = c1*c2
    c = c2**2
    
    K = member_props["E"]*member_props["A"]/length

    K2 = np.array([[ a , b , -a , -b] , 
             [ b , c , -b , -c],
             [-a , -b , a , b ],
             [-b , -c , b , c ]])

    K_mem = K * K2
    return( K_mem )

In [242]:
member_1 = {"E": 2.1E5 , "A" : 3958.4 , 
                "jointI": joint_nodes[3] , 
                "jointJ": joint_nodes[1]}
k = member_stiffness_creator(member_1)

print( k )

[[ 277088.       0. -277088.      -0.]
 [      0.       0.      -0.      -0.]
 [-277088.      -0.  277088.       0.]
 [     -0.      -0.       0.       0.]]


In [244]:
# Introducing a variable for Truss members. 
DOF = 2

In [243]:
joint_nodes = {1:[3000,0] , 2:[0,3000],3:[0,0],4:[3000,3000]}

In [248]:
member_nodes= {1:[3,1] , 2:[2,1],3:[1,4]}

In [245]:
member_1 = {"E": 2.1E5 , "A" : 3958.4 , 
                "jointI": joint_nodes[3] , 
                "jointJ": joint_nodes[1]}

In [246]:
member_2 = {"E": 2.1E5 , "A" : 3958.4 , 
                "jointI": joint_nodes[2] , 
                "jointJ": joint_nodes[1]}

In [247]:
member_3= {"E": 2.1E5 , "A" : 3958.4 , 
                "jointI": joint_nodes[1] , 
                "jointJ": joint_nodes[4]}

In [249]:
member_props = {}

for member_no , member_property in zip( member_nodes.keys() , [member_1 ,  member_2 , member_3]):
    
    member_props[ member_no ] = member_property   
    
member_props

{1: {'E': 210000.0, 'A': 3958.4, 'jointI': [0, 0], 'jointJ': [3000, 0]},
 2: {'E': 210000.0, 'A': 3958.4, 'jointI': [0, 3000], 'jointJ': [3000, 0]},
 3: {'E': 210000.0, 'A': 3958.4, 'jointI': [3000, 0], 'jointJ': [3000, 3000]}}

In [250]:
k_members = {}

for member_no , member_property in member_props.items() : 
    
    k_members[member_no] =  member_stiffness_creator(member_property  )
    
    
k_members

{1: array([[ 277088.,       0., -277088.,      -0.],
        [      0.,       0.,      -0.,      -0.],
        [-277088.,      -0.,  277088.,       0.],
        [     -0.,      -0.,       0.,       0.]]),
 2: array([[ 97965.40189271, -97965.40189271, -97965.40189271,
          97965.40189271],
        [-97965.40189271,  97965.40189271,  97965.40189271,
         -97965.40189271],
        [-97965.40189271,  97965.40189271,  97965.40189271,
         -97965.40189271],
        [ 97965.40189271, -97965.40189271, -97965.40189271,
          97965.40189271]]),
 3: array([[      0.,       0.,      -0.,      -0.],
        [      0.,  277088.,      -0., -277088.],
        [     -0.,      -0.,       0.,       0.],
        [     -0., -277088.,       0.,  277088.]])}

In [251]:
K = np.zeros( (len(joint_nodes) * DOF , len(joint_nodes) * DOF) , dtype=int)

print( K,"\n"+"="*100)

for truss_no , truss_node in member_nodes.items() :     
    
    k_temp = k_members[ truss_no]
    
    print( k_temp ,"\n"+"="*100)
    
    for counter_i , i in enumerate( truss_node ): 
        
        for counter_j , j in enumerate(truss_node) :
            
            print( i, j,"\n"+"="*100)
            
            add_k = k_temp[ counter_i * DOF  : counter_i * DOF + DOF  , counter_j * DOF  : counter_j * DOF + DOF  ] 
            
            print( add_k , "\n"+"="*100)
            
            if i == 1 and j == 1 : 
                K[ 0  : DOF  , 0  : DOF] = K[ 0  : DOF  , 0  : DOF ] + add_k
                
            else:
                K[ i * DOF - DOF  : i * DOF   , j * DOF - DOF : j * DOF  ] = K[ i * DOF - DOF  : i * DOF  , j * DOF - DOF : j * DOF  ] + add_k                             
            print( K )    

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]] 
[[ 277088.       0. -277088.      -0.]
 [      0.       0.      -0.      -0.]
 [-277088.      -0.  277088.       0.]
 [     -0.      -0.       0.       0.]] 
3 3 
[[277088.      0.]
 [     0.      0.]] 
[[     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [     0      0      0      0 277088      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]
 [     0      0      0      0      0      0      0      0]]
3 1 
[[-277088.      -0.]
 [     -0.      -0.]] 
[[      0       0       0       0       0       0       0       0]
 [      0       0       0       0       0       0     

## Truss System Solution Example

What about algorithm?

In [252]:
K

array([[ 375053,  -97965,  -97965,   97965, -277088,       0,       0,
              0],
       [ -97965,  375053,   97965,  -97965,       0,       0,       0,
        -277088],
       [ -97965,   97965,   97965,  -97965,       0,       0,       0,
              0],
       [  97965,  -97965,  -97965,   97965,       0,       0,       0,
              0],
       [-277088,       0,       0,       0,  277088,       0,       0,
              0],
       [      0,       0,       0,       0,       0,       0,       0,
              0],
       [      0,       0,       0,       0,       0,       0,       0,
              0],
       [      0, -277088,       0,       0,       0,       0,       0,
         277088]])

<img src="figures/4-truss_system_solution_1.png">

Challenge

- Once you have the system stiffness matrix, can you apply the BC to the matrix and obtain unknown displacements?

- HAving the displacements can you find out the unknown forces (SR)?

Your assignment #2 will cover this topic?

---

---


# Frame systems explanation

_A truss is a structure composed of beam and columns joined together at their end points._

<img src="figures/7-EQE512-FrameExplanation.png" width="40%">


<img src="figures/4-beam_stiffness_1.png" width="60%">

# Beam Element

Transformation matrix is identical, since the member orientation is horizontal (same reference frame)

**Freedom**

<img src="figures/8-EQE512-BeamMemberExplanation.png" width="80%">

**Global Stiffness Matrix**

<img src="figures/8-EQE512-BeamMemberStiffness.png" width="50%">

---


## Beam element stiffness matrix

In [ ]:
E = 30000 # N/mm2
A = 10000 # mm2
I = 100000 # N/mm2
L = 3000 #mm
x1i, x2i = 0,0
x1j, x2j = 3000,4000


In [ ]:
import numpy as np
K = np.zeros((6,6))
K

In [ ]:
########### PLEASE FILL THE MATRIX GIVEN BELOW IN YOUR MIDTERM EXAM ###########
def column_stiffness_matrix( x1i, x2i , x1j, x2j , E , A , I, L ):
    EAL3 = E * A / (L**3)
    twelveEIL5 = 12*E*I/(L**5)
    sizEIL3 = 6 * E * I / (L**3)
    twoEIL = 2 * E * I / (L)
    
    delta_1 = x1i - x1j
    delta_2 = x2i - x2j 
    
    K = np.array( [[],
                  [],
                  [],
                  [],
                  [],
                  []])
    return K 


In [ ]:
member_stiffness = column_stiffness_matrix( x1i, x2i , x1j, x2j , E , A , I, L )

# Loading 

<img src="figures/11-EQE512-Loads.PNG"   style="width:60%">

## Unloaded

_Similar to the Truss elements, the loads act on the nodes._


## Loaded

**Uniform Loading**

<img src="./figures/10a-EQE512-BeamLoading-Uniform.png" width="60%">

**Triangle Loading**

<img src="./figures/10b-EQE512-BeamLoading-Triangle.png" width="60%">

**Point Loading**

<img src="./figures/10c-EQE512-BeamLoading-SingleLoad.png" width="60%">

**Trapezoidal Loading**

<img src="./figures/10d-EQE512-BeamLoading-Trapz.png" width="60%">

**Solution :**

1. Obtain the equivalent end forces
2. Apply the obtained values in opposite directions at the nodes
3. Ignore the span loads

<img src="./figures/12-EQE512-Loads-Apply.PNG"   style="width:70%">


---

**NEXT WEEK**
The topics for the next week 

- "Frame Systems- Moment Resisting Frames"


<img src="http://worshiphousemedia.s3.amazonaws.com/images/main/s/st/bnt/st/seeyounextweek1.jpg" width="30%" >



